version: 0.2

phases:
  install:
    commands:
      - echo Installing TypeScript...
      - npm install -g typescript
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code
      - npm install
      - tsc
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/*