version: 0.2

phases:
  install:
    commands:
      - echo Installing TypeScript...
      - npm install -g typescript
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code
      - npm install
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/*