version: 0.2

phases:
  install:
    commands:
      - sudo apt-get -y update
      - sudo apt-get -y install nodejs npm
      - npm config set strict-ssl false
      - echo Installing TypeScript...
      - npm install -g typescript
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code
      - npm install
      - ng build --base-href /uvcockpit/
      - docker build -t uvcockpit .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
